package modular.game;

/*
 * SphereRenderer.java
 *
 * Renders the planet sphere that the player stands on.
 *
 * Java owns:
 *   - Sphere geometry (circle, screen projection, scale)
 *   - Gradient fallback appearance
 *   - Player figure rendering
 *   - Surface normal calculations
 *   - Entity marker rendering (dots/labels on sphere surface)
 *
 * Python owns (via texture file hook):
 *   - Sphere surface texture content
 *   - Generated via GGUF image model or rule-based synthesis
 *   - Written to: modular/game/textures/sphere_fn{N}.png
 *   - Java loads and tiles/maps it over the sphere geometry
 *   - If absent: Java uses procedural ice gradient (fully operational)
 *
 * PYTHON TEXTURE HOOK:
 *   When GoddessAPI.py's ImageGGUF or texture synthesis generates a surface,
 *   it writes the file and sends [WORLD_UPDATE:texture:sphere_fn{N}.png].
 *   GameProtocol receives the tag, sets WorldState.sphereTextureFile,
 *   and sets WorldState.textureReloadNeeded = true.
 *   SphereRenderer checks this flag each frame and reloads accordingly.
 *
 * Contributors:
 *   Gemini (Google)        — original ice sphere gradient concept
 *   Derek Jason Gilhousen — sphere-as-planet design, scale intent
 *   Claude (Anthropic)    — SphereRenderer, texture hook, player rendering
 */

import java.awt.*;
import java.awt.geom.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

public class SphereRenderer 
{
    // ── TEXTURE STATE ─────────────────────────────────────────────────────────
    private BufferedImage sphereTexture     = null;
    private File          lastTextureFile   = null;
    private TexturePaint  texturePaint      = null;

    // ── PLAYER FIGURE DIMENSIONS ──────────────────────────────────────────────
    // Player is rendered as a simple figure (stick figure V1, sprite later).
    // Scale relative to sphere screen radius so it always looks proportional.
    private static final float PLAYER_HEIGHT_RATIO = 0.55f;  // player/planet height ratio
    // Default: player 5.5ft, planet 3ft diameter → 5.5/3 ≈ 1.83
    // Inverted for screen: player screen height ≈ diameter * (5.5/3.0)

    // ── RENDER ────────────────────────────────────────────────────────────────

    public void render(Graphics2D g, WorldState world,
                       float centerX, float centerY,
                       float screenRadius, float altitudeScale) 
    {
        // Reload texture if Python has generated a new one
        maybeReloadTexture(world);

        // ── SPHERE BODY ───────────────────────────────────────────────────────
        Ellipse2D sphere = new Ellipse2D.Float(
            centerX - screenRadius,
            centerY - screenRadius,
            screenRadius * 2,
            screenRadius * 2
        );

        if (texturePaint != null) 
        {
            // [PYTHON HOOK: TEXTURE APPLIED]
            // Python-generated texture mapped over sphere.
            // Texture file generated by GGUF or rule-based synthesis.
            g.setPaint(texturePaint);
            g.fill(sphere);
        } 
        else 
        {
            // Procedural fallback — ice gradient (always operational)
            renderProceduralSphere(g, sphere, centerX, centerY, screenRadius);
        }

        // ── SPHERE RIM LIGHT ──────────────────────────────────────────────────
        g.setStroke(new BasicStroke(1.5f));
        g.setColor(new Color(255, 255, 255, 100));
        g.draw(sphere);

        // ── SURFACE POLE MARKERS ──────────────────────────────────────────────
        // Small dots at north and south poles for orientation
        g.setColor(new Color(200, 220, 255, 80));
        g.fillOval((int)(centerX - 2), (int)(centerY - screenRadius - 2), 4, 4);  // north
        g.fillOval((int)(centerX - 2), (int)(centerY + screenRadius - 2), 4, 4);  // south

        // ── ENTITY MARKERS ────────────────────────────────────────────────────
        // [PYTHON HOOK: ENTITY_SPAWN]
        // Entities populated via [ENTITY_SPAWN:] protocol tags from Python.
        // Rendered as small markers on the sphere surface.
        renderEntityMarkers(g, world, centerX, centerY, screenRadius);

        // ── PLAYER FIGURE ─────────────────────────────────────────────────────
        renderPlayer(g, world, centerX, centerY, screenRadius, altitudeScale);
    }

    // ── PROCEDURAL SPHERE ─────────────────────────────────────────────────────

    private void renderProceduralSphere(Graphics2D g, Ellipse2D sphere,
                                        float cx, float cy, float r) 
    {
        // Ice planet gradient — top lighter (lit), bottom deeper (dark side)
        GradientPaint ice = new GradientPaint(
            cx, cy - r, new Color(210, 235, 255, 230),
            cx, cy + r, new Color(80,  130, 200, 255)
        );
        g.setPaint(ice);
        g.fill(sphere);

        // Subtle specular highlight — upper left
        RadialGradientPaint highlight = new RadialGradientPaint(
            new Point2D.Float(cx - r * 0.3f, cy - r * 0.4f),
            r * 0.5f,
            new float[]{ 0f, 1f },
            new Color[]{ new Color(255, 255, 255, 80), new Color(255, 255, 255, 0) }
        );
        g.setPaint(highlight);
        g.fill(sphere);
    }

    // ── PLAYER FIGURE ─────────────────────────────────────────────────────────

    private void renderPlayer(Graphics2D g, WorldState world,
                              float cx, float cy, float screenRadius,
                              float altitudeScale) 
    {
        // Player height in screen pixels
        // 5.5ft player / 3ft planet diameter * diameter in pixels = player height px
        float planetDiam  = world.planetDiameterFeet;
        float playerH     = (world.playerHeightFeet / planetDiam) * screenRadius * 2;
        float playerW     = playerH * 0.3f;

        // Get screen position from physics
        float[] pos = getPlayerScreenPos(world, cx, cy, screenRadius, altitudeScale);
        float px = pos[0];
        float py = pos[1];

        double angleRad = Math.toRadians(world.playerAngleDeg);

        // Transform: rotate graphics context so figure stands upright
        // relative to the sphere surface at their angle
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Rotate to stand on surface normal
        g2.rotate(angleRad, px, py);

        // ── STICK FIGURE (V1) ─────────────────────────────────────────────────
        // [FUTURE HOOK: SPRITE]
        // Replace stick figure with sprite sheet when Python generates avatar.
        // Sprite file: modular/game/textures/player_sprite.png
        // Avatar style defined in image.xtx and avatar_choreography.txt.

        g2.setColor(new Color(230, 245, 255, 220));
        g2.setStroke(new BasicStroke(Math.max(1f, playerW * 0.25f),
                     BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));

        float headR  = playerH * 0.15f;
        float bodyT  = py - playerH;
        float bodyB  = py - playerH * 0.45f;
        float midY   = py - playerH * 0.65f;

        // Head
        g2.fillOval((int)(px - headR), (int)(bodyT - headR * 2), (int)(headR * 2), (int)(headR * 2));

        // Body
        g2.drawLine((int)px, (int)bodyT, (int)px, (int)bodyB);

        // Arms
        if (world.isJumping) 
        {
            // Arms up when jumping
            g2.drawLine((int)px, (int)midY, (int)(px - playerH * 0.22f), (int)(midY - playerH * 0.15f));
            g2.drawLine((int)px, (int)midY, (int)(px + playerH * 0.22f), (int)(midY - playerH * 0.15f));
        } 
        else 
        {
            // Arms relaxed
            g2.drawLine((int)px, (int)midY, (int)(px - playerH * 0.22f), (int)(midY + playerH * 0.1f));
            g2.drawLine((int)px, (int)midY, (int)(px + playerH * 0.22f), (int)(midY + playerH * 0.1f));
        }

        // Legs
        g2.drawLine((int)px, (int)bodyB, (int)(px - playerH * 0.12f), (int)py);
        g2.drawLine((int)px, (int)bodyB, (int)(px + playerH * 0.12f), (int)py);

        g2.dispose();
    }

    private float[] getPlayerScreenPos(WorldState world, float cx, float cy,
                                        float screenRadius, float altitudeScale) 
    {
        double rad  = Math.toRadians(world.playerAngleDeg);
        float  rimX = cx + screenRadius * (float)Math.sin(rad);
        float  rimY = cy - screenRadius * (float)Math.cos(rad);
        float  normX = (float)Math.sin(rad);
        float  normY = -(float)Math.cos(rad);
        float  altPx = world.playerAltitudeFeet * altitudeScale;
        return new float[]{ rimX + normX * altPx, rimY + normY * altPx };
    }

    // ── ENTITY MARKERS ────────────────────────────────────────────────────────

    private void renderEntityMarkers(Graphics2D g, WorldState world,
                                     float cx, float cy, float r) 
    {
        if (world.entities.isEmpty()) return;

        for (WorldState.GameEntity e : world.entities) 
        {
            double rad = Math.toRadians(e.angleDeg);
            float  ex  = cx + r * (float)Math.sin(rad);
            float  ey  = cy - r * (float)Math.cos(rad);

            // Color by entity type
            Color markerColor;
            switch (e.type) 
            {
                case "landmark": markerColor = new Color(250, 205, 104, 200); break;
                case "anomaly":  markerColor = new Color(239, 68,  68,  200); break;
                case "ruin":     markerColor = new Color(157, 80, 187, 200);  break;
                case "signal":   markerColor = new Color(80,  220, 120, 200); break;
                default:         markerColor = new Color(200, 200, 200, 150); break;
            }

            g.setColor(markerColor);
            g.fillOval((int)(ex - 3), (int)(ey - 3), 6, 6);

            // Label (small, above marker)
            if (e.label != null && !e.label.isEmpty()) 
            {
                g.setFont(new Font("Monospaced", Font.PLAIN, 7));
                g.setColor(new Color(markerColor.getRed(),
                                     markerColor.getGreen(),
                                     markerColor.getBlue(), 160));
                FontMetrics fm = g.getFontMetrics();
                g.drawString(e.label,
                             (int)(ex - fm.stringWidth(e.label) / 2.0f),
                             (int)(ey - 6));
            }
        }
    }

    // ── TEXTURE MANAGEMENT ────────────────────────────────────────────────────

    private void maybeReloadTexture(WorldState world) 
    {
        if (!world.textureReloadNeeded) return;
        world.textureReloadNeeded = false;

        if (world.sphereTextureFile == null || !world.sphereTextureFile.exists()) 
        {
            sphereTexture = null;
            texturePaint  = null;
            lastTextureFile = null;
            return;
        }

        if (world.sphereTextureFile.equals(lastTextureFile)) return;

        try 
        {
            sphereTexture = ImageIO.read(world.sphereTextureFile);
            lastTextureFile = world.sphereTextureFile;
            // Wrap texture as a repeating paint across the sphere surface
            texturePaint = new TexturePaint(sphereTexture,
                new Rectangle(0, 0, sphereTexture.getWidth(), sphereTexture.getHeight()));
        } 
        catch (IOException e) 
        {
            sphereTexture = null;
            texturePaint  = null;
        }
    }
}
